#!/bin/sh
#
# Initial system setup for bare metal perfSONAR test bed host
#

# Currently-supported version of VirtualBox.
VBOX_VERSION=7.0

die()
{
    echo "$@" 2>&1
    exit 1
}

if [ "$(id -nu)" != "root" ]
then
   die "This program must be run as root."
fi

if [ -e "/etc/redhat-release" ]
then

    echo "Setting up something Red Hat-flavored"

    # Install VirtualBox
    rpm --import https://www.virtualbox.org/download/oracle_vbox.asc
    dnf -y install dnf-utils
    yum-config-manager --add-repo https://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
    dnf -y makecache
    dnf -y install \
	VirtualBox-${VBOX_VERSION} \
	kernel-devel \
	elfutils-libelf-devel \
	gcc \
	perl \
	make
    /sbin/vboxconfig
    
    # Install Vagrant
    dnf install -y dnf-utils
    dnf-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dnf -y install vagrant

elif [ -e "/etc/debian_version" ]
then

    echo "Setting up something Debian-flavored"

    echo
    echo "*** WARNING:  THIS IS UNTESTED***"
    echo

    apt update

    # Required for VirtualBox
    apt -y install git make kernel-devel
    
    # Install Vagrant
    curl -s https://apt.releases.hashicorp.com/gpg \
	| gpg --dearmor \
	> tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]" \
	 "https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
	> /etc/apt/sources.list.d/hashicorp.list
    apt update
    apt -y install vagrant

else

    die "No idea how to support this OS.  Sorry."

fi


TESTBED_USER=testbed
if ! getent passwd "${TESTBED_USER}" > /dev/null
then
    useradd -c 'perfSONAR Testbed' testbed
fi

su - "${TESTBED_USER}" -c "vagrant plugin install netaddr"

TESTBED_HOME=$(getent passwd "${TESTBED_USER}" | cut -d: -f 6)
su - "${TESTBED_USER}" -c "git -C '${TESTBED_HOME}' clone https://github.com/perfsonar/testbed-bare-metal-host.git"

echo "Setup was Successful."
echo "Configuration is in ${TESTBED_HOME}/testbed-bare-metal-host." 

exit 0
