# List of bridgeable interfaces by Vagrant box type

{
  "almalinux/8": [
    # Vagrant uses enp0s3 for NAT
    "enp0s8",
    "enp0s9",
    "enp0s10",
    "enp0s16",
    "enp0s17",
    "enp0s18",
    "enp0s19"
    ],

  "almalinux/9": [
    # TODO: This has been "casually" verified.  This vagrant box has
    # problems that prevent it from coming fully up.
    # Vagrant uses enp0s3 for NAT
    "enp0s8"
    ],
  "centos/7": [
    # Vagrant uses eth0 for NAT
    "eth1",
    "eth2",
    "eth3",
    "eth4",
    "eth5",
    "eth6",
    "eth7"
    ],

  "generic/debian10": [
    # Vagrant uses eth0 for NAT
    "eth1",
    "eth2",
    "eth3",
    "eth4",
    "eth5",
    "eth6",
    "eth7"
    ]
}